# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  clean:
    desc: Run tts.clean_text
    cmds:
      - uv run -m tts.clean_text {{.CLI_ARGS}}
  run_tts:
    desc: Run tts.run_tts
    cmds:
      - uv run -m tts.run_tts {{.CLI_ARGS}}
  pipeline:
    desc: Run tts.pipeline
    cmds:
      - uv run -m tts.pipeline {{.CLI_ARGS}}
